#!/bin/sh
#
# chkconfig: - 99 99
# description: Starts and stops the <service> daemons
#
# pidfile: /var/run/<service>/<service_name>.pid
# config: /etc/<service>/<service_name>.conf

# Source function library.
if [ -f /etc/init.d/functions ] ; then
    . /etc/init.d/functions
elif [ -f /etc/rc.d/init.d/functions ] ; then
    . /etc/rc.d/init.d/functions
else
    exit 1
fi

start() {
    echo "$0 running"
    return 0
}

stop() {
    echo "$0 stopped"
    return 0
}

restart() {
    return 0
}

reload() {
    return 0
}

rhstatus() {
    echo "$0 running well"
    return 0
}

case "$1" in
  start)
  start
;;
  stop)
  stop
;;
  restart)
  restart
;;
  reload)
  reload
;;
  status)
  rhstatus
;;
  condrestart)
  [ -f /var/lock/subsys/smb ] && restart || :
;;
  *)
  echo $"Usage: $0 {start|stop|restart|reload|status|condrestart}"
  exit 2
esac

exit $?
